# Generated by Django 3.1.4 on 2021-01-06 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='created_dt',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='topic',
            old_name='created_dt',
            new_name='created_date',
        ),
    ]
